import type { RequestHandler } from 'express';
import { z } from 'zod';
import type { CommandService } from '../services/command-service.js';
const createSchema=z.object({deviceId:z.string().uuid(),type:z.string(),version:z.number().int(),payload:z.unknown(),idempotencyKey:z.string().min(1).max(128).nullable().optional(),correlationId:z.string().min(1).max(128).nullable().optional()}).strict();
const idSchema=z.object({commandId:z.string().uuid()}).strict();
const toCommand=(c:any)=>({...c,createdAt:c.createdAt.toISOString(),expiresAt:c.expiresAt.toISOString(),deliveryAt:c.deliveryAt?.toISOString()??null,acknowledgedAt:c.acknowledgedAt?.toISOString()??null,startedAt:c.startedAt?.toISOString()??null,completedAt:c.completedAt?.toISOString()??null,cancelledAt:c.cancelledAt?.toISOString()??null});
export const createCommandController=(service:CommandService)=>({
 create:(async(req,res,next)=>{try{if(!req.authenticatedAdmin){res.status(401).json({error:{code:'AUTHENTICATION_REQUIRED',message:'Administrator authentication is required.'},requestId:res.locals.requestId});return;}const b=createSchema.safeParse(req.body);if(!b.success){res.status(400).json({error:{code:'INVALID_REQUEST',message:'Invalid command request.'},requestId:res.locals.requestId});return;}const r=await service.create(req.authenticatedAdmin.id,{deviceId:b.data.deviceId,type:b.data.type,version:b.data.version,payload:b.data.payload,idempotencyKey:b.data.idempotencyKey??null,correlationId:b.data.correlationId??null});res.status(r.created?201:200).json({data:{command:toCommand(r.command),created:r.created},requestId:res.locals.requestId});}catch(e){next(e);}}) as RequestHandler,
 get:(async(req,res,next)=>{try{const p=idSchema.safeParse(req.params);if(!p.success){res.status(400).json({error:{code:'INVALID_REQUEST',message:'Invalid command identifier.'},requestId:res.locals.requestId});return;}if(!req.authenticatedAdmin){res.status(401).json({error:{code:'AUTHENTICATION_REQUIRED',message:'Administrator authentication is required.'},requestId:res.locals.requestId});return;}const c=await service.getOwned(p.data.commandId,req.authenticatedAdmin.id);res.status(200).json({data:{command:toCommand(c)},requestId:res.locals.requestId});}catch(e){next(e);}}) as RequestHandler,
 cancel:(async(req,res,next)=>{try{const p=idSchema.safeParse(req.params);if(!p.success||!req.authenticatedAdmin){res.status(p.success?401:400).json({error:{code:p.success?'AUTHENTICATION_REQUIRED':'INVALID_REQUEST',message:p.success?'Administrator authentication is required.':'Invalid command identifier.'},requestId:res.locals.requestId});return;}const c=await service.cancel(p.data.commandId,req.authenticatedAdmin.id);res.status(200).json({data:{command:toCommand(c)},requestId:res.locals.requestId});}catch(e){next(e);}}) as RequestHandler,
});
