import type {RequestHandler} from 'express';
import {z} from 'zod';
import type {CommandService} from '../services/command-service.js';
const createSchema=z.object({managedDeviceId:z.string().uuid(),type:z.literal('FUTURE_COMMAND'),version:z.literal(1),payload:z.record(z.string(),z.unknown()).default({}),expiresAt:z.string().datetime().optional()}).strict();
const idSchema=z.object({commandId:z.string().uuid()}).strict();
const response=(c:any)=>({id:c.id,managedDeviceId:c.managedDeviceId,adminId:c.adminId,type:c.type,version:c.version,status:c.status,payload:c.payload,correlationId:c.correlationId,idempotencyKey:c.idempotencyKey,createdAt:c.createdAt.toISOString(),expiresAt:c.expiresAt.toISOString(),deliveryAt:c.deliveryAt?.toISOString()??null,acknowledgedAt:c.acknowledgedAt?.toISOString()??null,startedAt:c.startedAt?.toISOString()??null,completedAt:c.completedAt?.toISOString()??null,cancelledAt:c.cancelledAt?.toISOString()??null,failureCode:c.failureCode,errorCategory:c.errorCategory,resultCode:c.resultCode,resultMetadata:c.resultMetadata});
export const createCommandController=(service:CommandService)=>({
 create:(async(req,res,next)=>{const p=createSchema.safeParse(req.body);const admin=req.authenticatedAdmin;const key=req.header('idempotency-key');if(!p.success||admin===undefined){res.status(400).json({error:{code:'INVALID_REQUEST',message:'Invalid command request.'},requestId:res.locals.requestId});return;}try{const result=await service.create({adminId:admin.id,managedDeviceId:p.data.managedDeviceId,type:p.data.type,version:p.data.version,payload:p.data.payload,idempotencyKey:key??null,expiresAt:p.data.expiresAt===undefined?undefined:new Date(p.data.expiresAt)});res.status(result.created?201:200).json({data:{command:response(result.command),created:result.created},requestId:res.locals.requestId});}catch(e){next(e);}}) as RequestHandler,
 get:(async(req,res,next)=>{const p=idSchema.safeParse(req.params);const admin=req.authenticatedAdmin;if(!p.success||admin===undefined){res.status(400).json({error:{code:'INVALID_REQUEST',message:'Invalid command identifier.'},requestId:res.locals.requestId});return;}try{const c=await service.getOwned(p.data.commandId,admin.id);res.status(200).json({data:{command:response(c)},requestId:res.locals.requestId});}catch(e){next(e);}}) as RequestHandler,
 cancel:(async(req,res,next)=>{const p=idSchema.safeParse(req.params);const admin=req.authenticatedAdmin;if(!p.success||admin===undefined){res.status(400).json({error:{code:'INVALID_REQUEST',message:'Invalid command identifier.'},requestId:res.locals.requestId});return;}try{const c=await service.cancel(p.data.commandId,admin.id);res.status(200).json({data:{command:response(c)},requestId:res.locals.requestId});}catch(e){next(e);}}) as RequestHandler,
});